### ISSUE TITLE
Server responding 401 error 

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#51]
When using the proctor exam test code provided, this is not generating a successful log in.  Tested this using the pre-cooked professor/student logins. 

<img width="765" alt="Screen Shot 2020-04-13 at 2 46 22 PM" src="https://user-images.githubusercontent.com/60198845/79149873-ceb83800-7d95-11ea-847a-fa9ddf23a62c.png">

**Comment by cucucachu** [comment]
I believe this issue should be solved by the work done under issue #83. Now the front-end redirects a user to the login screen when it recieves any 401 status from the backend. I think the original problem was probably due to stale session cookie and that should now be fixed. 

@elicaballero , you can retest and close if this is no longer an issue.

**Comment by cucucachu** [comment]
Closing, Not Done, but probably fixed since first reported
