### ISSUE TITLE
Uncaught error on console : csv files are not consistently loading  

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#65]
Tested on 4/21/2020 1:11

Was able to load the StudentRoster.csv without loading the ProfessorRoster. Seems to be an issue with ProfessorRoster. 

<img width="586" alt="Screen Shot 2020-04-21 at 1 12 12 PM" src="https://user-images.githubusercontent.com/60198845/79893430-119b9080-83d2-11ea-88b2-cccdea2af935.png">

**Comment by elicaballero** [comment]
Digging deeper into the error messages being received. Error message shows professors are already created for the school. Verified there no professors saved on front end. 

<img width="846" alt="Screen Shot 2020-04-21 at 1 26 15 PM" src="https://user-images.githubusercontent.com/60198845/79894777-f467c180-83d3-11ea-8aaa-2ffec4a3bdb8.png">

**Comment by cucucachu** [comment]
On the first point 'able to load student roster without loading professor roster'. 

This should now be prevented by changes for issue #64.

On the second point, I have added better error handling, so that if one of the two files is uploaded successfully, and the other is not, all the students and professors for the school are cleared, allowing the admin to attempt upload again.
