### ISSUE TITLE
Scalability Testing

### ISSUE THREAD

**Issue by elicaballero** [cucucachu/wise-online-backend#70]
> This ticket will be used to measure Scalability issues/concerns

**Comment by cucucachu** [comment]
I'm going to use this ticket to write load testing scripts. To start, here is what I'd like.

- Upload csv files with 10000 students and 1000 professors. 
- Take attendance for course. 100 students per attendances. We can run this one with increasing numbers of courses to see how we scale.
- Take test for course. 100 students per test. Increasing numbers of courses.

**Comment by elicaballero** [comment]
tested 4/30/2020
5:19 pm EST 

Tried to upload a csv with 1000 students / 100 professors. The cvs begins to load but quits. Im getting an error message on the front end but nothing is showing in console. 

<img width="1053" alt="Screen Shot 2020-04-30 at 5 20 41 PM" src="https://user-images.githubusercontent.com/60198845/80760691-4d87d180-8b07-11ea-809f-e4568123593b.png">

Went through multiple uploads with various amounts of students and I noticed another concern: 
When uploading a csv with 100 students and 100 professors. I received an error message but the the csv was still uploaded on the back end. 

<img width="613" alt="Screen Shot 2020-04-30 at 6 47 32 PM" src="https://user-images.githubusercontent.com/60198845/80766291-17504f00-8b13-11ea-9e29-0d7d48eb2880.png">

**Comment by elicaballero** [comment]
Note: Attendance and Test codes are working as expected with all users accounted for with in the CSV. Also all student account are able to log in, also attendance is being tracked per student log in.

**Comment by cucucachu** [comment]
@elicaballero 

The first error you encountered seems to be the timeout issue. I see taylor has now addressed this, but not sure if it's been deployed yet.

The second is likely related. When the first try timesout, but the students are uploaded successfully (as seems to be the case) then the school is considered set up and you recieve this error.

**Comment by cucucachu** [comment]
I have a new script for performance testing. 

First I seed the database with a school with 100 professors (1 course each) and 10000 students. 

To test attendance performance, I loop through professors/courses and start attendance, I then have 100 students mark attendance for each course. 

When testing sequentially (no parallel requests) for a single course with 100 students, it takes around 30 seconds to process. This is not entirely the servers processing time, some of this is network latency.

When I test taking attendance for 2 courses, in parallel, the total time is about 35 seconds. Since this is a 2x increase in the number of requests, but only a ~17% increase in total time, this shows that the defining factor is probably the network latency and my computer, not the server. 

I think this shows that we are ready for our first few schools, as humans are unlikely to be able to fit so many requests into such a short time period. 

Also checked the app engine instances. Instances created/active does spike due to the load, but they spin down within a minute or two once load subsides.

**Comment by elicaballero** [comment]
After trying to upload a csv with 500 students and 500 professors. That's probably an unlikely number but I'm receiving this error message. Any concern here?

<img width="719" alt="Screen Shot 2020-05-11 at 4 10 11 PM" src="https://user-images.githubusercontent.com/60198845/81607085-1a183300-93a2-11ea-9cbb-223404551db1.png">

**Comment by cucucachu** [comment]
This is likely a functional bug rather than a performance issue. Looking into it.

**Comment by cucucachu** [comment]
I figured out what was going on with that 'Forbidden' message. During set up school, it attempted to send out the onboarding emails. We hit the 100 emails/day limit on the free tier for sendgrid, and thats where the forbidden comes from. 

Working with Ian to move out of the free tier to 40000 emails/month, which will fix this issue.
